baseURL = 'https://blog.douchi.space/public'
languageCode = 'zh-CN'
title = '椒盐豆豉'
theme = 'hugo-book'
hasCJKLanguage = true
enableRobotsTXT = true

googleAnalytics = "G-0R5FWRP8MH"
disqusShortname = "mtfront"

[markup]
    [markup.highlight]
        style = 'paraiso-light'     # style demos https://pygments.org/demo/
    
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[params]
    BookRepo = 'https://github.com/mtfront/mtfront'
    BookLogo = 'dino.gif'
    BookMenuBundle = '/menu'

[services.rss]
    limit = 10

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^GITHUB_REFERER$']